project_id = "jknouttcuwbvygkobrff"

[functions.recommend-resin]
verify_jwt = false

[functions.analyze-photos]
verify_jwt = false

[functions.analyze-dental-photo]
verify_jwt = false

[functions.generate-dsd]
verify_jwt = false

[functions.recommend-cementation]
verify_jwt = false